name: Sync
on:
    push:
        branches:
            - test_gh
jobs:
    sync:
        name: sync-to-gitlab
        runs-on: ubuntu-latest
        steps:
            # - uses: actions/checkout@v3
            - uses: webfactory/ssh-agent@v0.7.0
              with:
                  ssh-private-key: ${{ secrets.MY_SSH_PRIVATE_KEY }}
            - run: git clone --mirror ${{ vars.REPO_URL }}
#            - run: git remote set-url --push origin git@github.com:PhilA1/syncmirror.git
#              working-directory: ./aws.codepipeline.example.git
#            - run: git fetch -p origin
#              working-directory: ./aws.codepipeline.example.git
#            - run: git push --mirror
#              working-directory: ./aws.codepipeline.example.git
